#!/bin/sh
echo "Setting environment variables for Terraform"
export ARM_SUBSCRIPTION_ID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export TF_VAR_subscription_id=$ARM_SUBSCRIPTION_ID
export ARM_CLIENT_ID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export TF_VAR_client_id=$ARM_CLIENT_ID
export ARM_CLIENT_SECRET=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export TF_VAR_client_secret=$ARM_CLIENT_SECRET
export ARM_TENANT_ID=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
export TF_VAR_tenant_id=$ARM_TENANT_ID

